server:
  port: 8080
spring:
  datasource:
    druid:
      db1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://rm-bp1977ym6gh4afdao.mysql.rds.aliyuncs.com:3306/payment?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: payment
        password: 7Jy&5Vy=3Me^0Ns=7Lu(2Fa*1J
      db2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://rm-bp1977ym6gh4afdao.mysql.rds.aliyuncs.com:3306/payment?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: payment
        password: 7Jy&5Vy=3Me^0Ns=7Lu(2Fa*1J
  redis:
    host: 192.168.30.55
    port: 6379
    database: 7
    password:
logging:
  level:
    com.otechsolution: info
    io.swagger.models.parameters.AbstractSerializableParameter: error

com:
  otech:
    forex:
      client-info:
        auth-url: https://top.otechsolution.com/api/DeskTop/GetClient
        require-url: /api/**
        ignore-url:
swagger:
  enable: false